[package]
name = "roi"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4"
crossterm = "0.27"
ratatui = { version = "0.26", default-features = false, features = ["crossterm"] }
csv = "1.3"
